version: '3.8'

services:
  db:
    container_name: baby_food_tracker_db
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: baby_food_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    container_name: baby_food_tracker_test_db
    image: postgres:14-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: baby_food_tracker_test
    tmpfs: 
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=2G # Using tmpfs for faster test database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: