version: '3.8'

services:
  db:
    container_name: baby_food_tracker_db
    image: postgres:14-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    container_name: baby_food_tracker_test_db
    image: postgres:14-alpine
    ports:
      - "5436:5432"  # Keeping this fixed for test DB
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    tmpfs: 
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=2G

volumes:
  pgdata: