version: '3.8'

services:
  app:
    container_name: baby_food_tracker_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.production
    ports:
      - "3000:3000"
    depends_on:
      prod_db:
        condition: service_healthy

  prod_db:
    container_name: baby_food_tracker_prod_db
    image: postgres:14-alpine
    env_file: .env.production
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  prod_postgres_data: