services:
  - type: web
    name: baby-food-tracker-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    preDeployCommand: npm run migration:run  # This will run before the service starts
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: baby-food-tracker-db
          property: connectionString

databases:
  - name: baby-food-tracker-db
    plan: free
    ipAllowList: []