services:
  - type: web
    name: baby-food-tracker-api
    env: node
    buildCommand: npm ci && npm run build && npm run db:migrate:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: baby-food-tracker-db
          property: connectionString

databases:
  - name: baby-food-tracker-db
    plan: free
    ipAllowList: []