name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          POSTGRES_DB: baby_food_tracker_test
        ports:
          - 5436:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      env:
        NODE_ENV: test
        JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
        DB_HOST: localhost
        DB_PORT: 5436
        DB_USER: ${{ secrets.TEST_DB_USER }}
        DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        DB_NAME: baby_food_tracker_test
      run: npm test